// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6w0P4p-1-eO9ixL66iiwVzzLujZvQgJs',
    appId: '1:567509991377:web:554c99934e0d1c66a06af0',
    messagingSenderId: '567509991377',
    projectId: 'weatherfreeapp',
    authDomain: 'weatherfreeapp.firebaseapp.com',
    storageBucket: 'weatherfreeapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-pjl3PaV2ucCxuXI1N6a6siRMWydO9XA',
    appId: '1:567509991377:android:469719597ad3d0d0a06af0',
    messagingSenderId: '567509991377',
    projectId: 'weatherfreeapp',
    storageBucket: 'weatherfreeapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpmT68UfDNQoceEJhwnSlv7HuPWKung_A',
    appId: '1:567509991377:ios:84fb7761bcb321dca06af0',
    messagingSenderId: '567509991377',
    projectId: 'weatherfreeapp',
    storageBucket: 'weatherfreeapp.firebasestorage.app',
    androidClientId: '567509991377-75joqgoufmd0b99je4pqo1kskfsduc99.apps.googleusercontent.com',
    iosClientId: '567509991377-ae82q5icc2np9ogdqdj2k1cg09tq9gkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherfreeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpmT68UfDNQoceEJhwnSlv7HuPWKung_A',
    appId: '1:567509991377:ios:84fb7761bcb321dca06af0',
    messagingSenderId: '567509991377',
    projectId: 'weatherfreeapp',
    storageBucket: 'weatherfreeapp.firebasestorage.app',
    androidClientId: '567509991377-75joqgoufmd0b99je4pqo1kskfsduc99.apps.googleusercontent.com',
    iosClientId: '567509991377-ae82q5icc2np9ogdqdj2k1cg09tq9gkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherfreeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6w0P4p-1-eO9ixL66iiwVzzLujZvQgJs',
    appId: '1:567509991377:web:224e8654f5d50bb2a06af0',
    messagingSenderId: '567509991377',
    projectId: 'weatherfreeapp',
    authDomain: 'weatherfreeapp.firebaseapp.com',
    storageBucket: 'weatherfreeapp.firebasestorage.app',
  );
}
